
Skip to content
Pull requests
Issues
Marketplace
Explore
@jbusecke
pangeo-data /
pangeo-example-notebooks

13
57

    41

Code
Issues 9
Pull requests 2
Actions
Projects 0
Wiki
Security 0

    Insights

pangeo-example-notebooks/.dask/config.yaml
@jhamman jhamman update binder environment f380ea8 on Oct 30, 2018
42 lines (38 sloc) 753 Bytes
fuse_subgraphs: False
fuse_ave_width: 0

distributed:
  logging:
    bokeh: critical

  dashboard:
    link: /user/{JUPYTERHUB_USER}/proxy/{port}/status

  admin:
    tick:
      limit: 5s

kubernetes:
  count:
    max: 50
  worker-template:
    metadata:
    spec:
      nodeSelector:
        dask-worker: True
      restartPolicy: Never
      containers:
      - args:
          - dask-worker
          - --nthreads
          - '2'
          - --no-bokeh
          - --memory-limit
          - 7GB
          - --death-timeout
          - '60'
        image: ${JUPYTER_IMAGE_SPEC}
        name: dask-worker
        resources:
          limits:
            cpu: "1.75"
            memory: 7G
          requests:
            cpu: 1
            memory: 7G

    © 2020 GitHub, Inc.
    Terms
    Privacy
    Security
    Status
    Help

    Contact GitHub
    Pricing
    API
    Training
    Blog
    About


