name: earthcube-notebook-jbusecke
channels:
  - conda-forge
dependencies:
  - cartopy
  - cftime
  - fsspec
  - gcsfs
  - matplotlib
  - nc-time-axis
  - netcdf4
  - pangeo-notebook=2020.05.04
  - pip
  - proplot
  - s3fs
  - watermark
  - zarr
  - pip:
      - git+https://github.com/jbusecke/cmip6_preprocessing.git@refs/pull/46/head
      - git+https://github.com/xgcm/xgcm.git
      - git+https://github.com/NCAR/intake-esm.git
      
